// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Employee.proto

package com.example.producer.proto;

public final class EmployeeProducerEvent {
  private EmployeeProducerEvent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demoproducer_Employee_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demoproducer_Employee_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Employee.proto\022\014demoproducer\"l\n\010Employ" +
      "ee\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\016\n\006salary\030\003" +
      " \001(\001\022\023\n\013designation\030\004 \001(\t\022\016\n\006gender\030\005 \001(" +
      "\t\022\021\n\toperation\030\006 \001(\tB5\n\032com.example.prod" +
      "ucer.protoB\025EmployeeProducerEventP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_demoproducer_Employee_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demoproducer_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demoproducer_Employee_descriptor,
        new java.lang.String[] { "Id", "Name", "Salary", "Designation", "Gender", "Operation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
