// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Employee.proto

package com.example.producer.proto;

public interface EmployeeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:demoproducer.Employee)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>double salary = 3;</code>
   * @return The salary.
   */
  double getSalary();

  /**
   * <code>string designation = 4;</code>
   * @return The designation.
   */
  java.lang.String getDesignation();
  /**
   * <code>string designation = 4;</code>
   * @return The bytes for designation.
   */
  com.google.protobuf.ByteString
      getDesignationBytes();

  /**
   * <code>string gender = 5;</code>
   * @return The gender.
   */
  java.lang.String getGender();
  /**
   * <code>string gender = 5;</code>
   * @return The bytes for gender.
   */
  com.google.protobuf.ByteString
      getGenderBytes();

  /**
   * <code>string operation = 6;</code>
   * @return The operation.
   */
  java.lang.String getOperation();
  /**
   * <code>string operation = 6;</code>
   * @return The bytes for operation.
   */
  com.google.protobuf.ByteString
      getOperationBytes();
}
